# Generated by Django 4.2.4 on 2023-10-21 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('router', models.CharField(default='Mercusi', max_length=30)),
                ('n_serie', models.BigIntegerField(default=1234567893)),
                ('estado', models.CharField(choices=[['A', 'A'], ['B', 'B'], ['S', 'S']], default='A', max_length=1)),
                ('observaciones', models.TextField()),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_plan', models.CharField(max_length=45)),
                ('cantidad_megas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_deuda', models.CharField(max_length=20)),
                ('año_deuda', models.IntegerField()),
                ('fecha_pago', models.DateField(null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.zona'),
        ),
    ]
