# Generated by Django 4.2.4 on 2023-10-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientedeuda',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientedeuda',
            name='mes_deuda',
            field=models.CharField(choices=[['Enero', 'Enero'], ['Febrero', 'Febrero'], ['Marzo', 'Marzo'], ['Abril', 'Abril'], ['Mayo', 'Mayo'], ['Junio', 'Junio'], ['Julio', 'Julio'], ['Agosto', 'Agosto'], ['Septiembre', 'Septiembre'], ['Octubre', 'Octubre'], ['Noviembre', 'Noviembre'], ['Diciembre', 'Diciembre']], max_length=20),
        ),
    ]
