# Generated by Django 4.2.4 on 2023-10-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientedeuda_monto_pagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_deuda', models.CharField(choices=[['Enero', 'Enero'], ['Febrero', 'Febrero'], ['Marzo', 'Marzo'], ['Abril', 'Abril'], ['Mayo', 'Mayo'], ['Junio', 'Junio'], ['Julio', 'Julio'], ['Agosto', 'Agosto'], ['Septiembre', 'Septiembre'], ['Octubre', 'Octubre'], ['Noviembre', 'Noviembre'], ['Diciembre', 'Diciembre']], max_length=20)),
                ('año_deuda', models.IntegerField()),
                ('fecha_pago', models.DateField(null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ManyToManyField(to='clientes.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='ClienteDeuda',
        ),
    ]
