# Generated by Django 4.2.4 on 2023-10-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_rename_cliente_clientedeuda_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientedeuda',
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='cliente',
            new_name='clientes',
        ),
    ]
