# Generated by Django 4.2.4 on 2023-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_deuda_clientes_cliente_deudas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
