# Generated by Django 4.2.4 on 2023-11-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_servicio_idservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
