# Generated by Django 4.2.4 on 2023-11-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_deuda_unique_together'),
        ('clientes', '0013_alter_zona_id'),
    ]

    operations = [
    ]
