# Generated by Django 4.2.4 on 2023-11-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_zona_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('idmapa', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='ubicacion_en_mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.mapa'),
        ),
    ]
