# Generated by Django 4.2.4 on 2023-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_remove_cliente_ubicacion_en_mapa_delete_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
