# Generated by Django 4.2.4 on 2023-11-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_zona_latitud_zona_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='longitud',
        ),
    ]
