# Generated by Django 4.2.4 on 2023-11-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_zona_latitud_remove_zona_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='zona',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
