# Generated by Django 4.2.4 on 2023-11-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_merge_20231114_2017'),
        ('clientes', '0018_zona_latitud_zona_longitud'),
    ]

    operations = [
    ]
